---

networks:
  internal:
    name: traefik-internal
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/24


services:

  traefik:
    hostname: traefik
    restart: unless-stopped
    image: traefik:v3.2
    container_name: traefik
    networks:
      internal:
        ipv4_address: 172.20.20.20
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "/usr/share/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
