---
networks:
  internal:
    name: internal
    external: true


services:

  traefik:
    hostname: traefik
    restart: unless-stopped
    image: traefik:v3.2
    container_name: traefik
    networks:
      internal:
        ipv4_address: 10.10.10.100
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
