---
networks:
  internal:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

services:

  cloudflared:
    hostname: cloudflared
    restart: unless-stopped
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.2.0
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TOKEN}
    labels:
      - "traefik.enable=false"
    networks:
      internal:
        ipv4_address: 10.10.10.10