---
networks:
  internal:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24

services:

  cloudflared:
    hostname: cloudflared
    restart: unless-stopped
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.2.0
    command: tunnel --no-autoupdate run --token $TOKEN
    networks:
      internal:
        ipv4_address: 172.30.30.30