version: "3.6"

networks:
  internal:
    name: postgres-internal
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.30.30.0/24


services:

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:13.11-alpine
    expose: [ 5432 ]
    ports:
      - 5432:5432
    networks:
      internal:
        ipv4_address: 172.30.30.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dSrBmWg8swFKi694CJ5Av9QAh4hFuiGK

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:8080
    networks:
      internal:
        ipv4_address: 172.30.30.20
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.org
      PGADMIN_DEFAULT_PASSWORD: dSrBmWg8swFKi694CJ5Av9QAh4hFuiGK
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 8080
